pipeline {
    agent any
    
    parameters {
        booleanParam(name: 'BUILD_DOCKER', defaultValue: false, description: 'Build and push Docker image?')
    }
    
    environment {
        DOCKER_IMAGE = 'patcreator/messaging-app:latest'
        DOCKER_USERNAME = 'patcreator'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/PATCREATOR/alx-backend-python.git',
                    credentialsId: 'github-credentials'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                        pip3 install --upgrade pip
                        pip3 install -r messaging_app/requirements.txt
                        pip3 install pytest pytest-django
                    '''
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                        pytest --junitxml=test-reports/results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-reports/*.xml'
                }
            }
        }
        
        stage('Build Docker Image') {
            when {
                expression { params.BUILD_DOCKER }
            }
            steps {
                dir('messaging_app') {
                    sh '''
                        docker build -t messaging-app:latest .
                        docker tag messaging-app:latest $DOCKER_USERNAME/messaging-app:latest
                    '''
                }
            }
        }
        
        stage('Push to Docker Hub') {
            when {
                expression { params.BUILD_DOCKER }
            }
            steps {
                withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USERNAME --password-stdin
                        docker push $DOCKER_USERNAME/messaging-app:latest
                    '''
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}